/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopscafe;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nyarsh
 */
public class oopscafeGUI extends javax.swing.JFrame {

    /**
     * Creates new form oopscafeGUI
     */
    
    private Order currentOrder = new Order("Customer", 1);
    private String selectedCategory = "Hot";
    private String selectedSize = null;
    private DefaultTableModel tableModel;
    private javax.swing.JPanel menuContentPanel = new javax.swing.JPanel();
    
    public oopscafeGUI() {
    initComponents();
    setupTable();
    txtTotalItems.setText("0");
    txtTotalAmt.setText("₱0.00");
    btnEncap.setEnabled(false);

    // Set up panelMenu with fixed top bar and scrollable content below
    panelMenu.setLayout(new java.awt.BorderLayout());

    // Top bar - created ONCE, never removed
    javax.swing.JPanel topBar = new javax.swing.JPanel(
    new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
topBar.setBackground(panelMenu.getBackground());
topBar.setPreferredSize(new java.awt.Dimension(Integer.MAX_VALUE, 40));
topBar.setMinimumSize(new java.awt.Dimension(0, 40));
topBar.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 40));
txtsearchfield.setPreferredSize(new java.awt.Dimension(350, 30)); // ← longer
txtsearchfield.setMinimumSize(new java.awt.Dimension(350, 30));   // ← steady
txtsearchfield.setMaximumSize(new java.awt.Dimension(350, 30));   // ← steady
topBar.add(jLabel7);
topBar.add(txtsearchfield);
topBar.add(btnSearch);
panelMenu.add(topBar, java.awt.BorderLayout.NORTH);

    // Content panel - this is what gets rebuilt on search
    menuContentPanel.setLayout(new javax.swing.BoxLayout(
        menuContentPanel, javax.swing.BoxLayout.Y_AXIS));
    menuContentPanel.setBackground(panelMenu.getBackground());
    panelMenu.add(menuContentPanel, java.awt.BorderLayout.CENTER);

    loadMenu("");

    txtsearchfield.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtsearchfield.getText().equals("Search Drink")) {
                txtsearchfield.setText("");
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtsearchfield.getText().isEmpty()) {
                txtsearchfield.setText("Search Drink");
            }
        }
    });

    txtsearchfield.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filterMenu(txtsearchfield.getText());
        }
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filterMenu(txtsearchfield.getText());
        }
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filterMenu(txtsearchfield.getText());
        }
    });
}
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnHot = new javax.swing.JButton();
        btnCold = new javax.swing.JButton();
        btnMilktea = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEncap = new javax.swing.JButton();
        btnInhe = new javax.swing.JButton();
        btnPoly = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        scrollMenu = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtsearchfield = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        btnClearOrder = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTotalItems = new javax.swing.JLabel();
        txtTotalAmt = new javax.swing.JLabel();
        txtTotalItems = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopscafe/oops_cafe_background_992w.png"))); // NOI18N
        jLabel1.setText("OOP's CAFE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(233, 217, 187));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("ChooseCategory");

        btnHot.setText("♨ Hot Coffee");
        btnHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotActionPerformed(evt);
            }
        });

        btnCold.setText("❄ Iced Coffee");
        btnCold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColdActionPerformed(evt);
            }
        });

        btnMilktea.setText("◉ Milk Tea");
        btnMilktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilkteaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Choose Size");

        btnEncap.setText("◔ ENCAP");
        btnEncap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncapActionPerformed(evt);
            }
        });

        btnInhe.setText("◑ INHE");
        btnInhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInheActionPerformed(evt);
            }
        });

        btnPoly.setText("◕ POLY");
        btnPoly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel4.setText("SMALL");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel5.setText("MEDIUM");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel6.setText("LARGE");

        jSeparator1.setBackground(new java.awt.Color(120, 97, 69));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHot)
                        .addGap(44, 44, 44)
                        .addComponent(btnCold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMilktea)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnEncap)
                                .addGap(44, 44, 44)
                                .addComponent(btnInhe)
                                .addGap(43, 43, 43)
                                .addComponent(btnPoly)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel5)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6)
                        .addGap(48, 48, 48))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPoly)
                                    .addComponent(btnInhe)
                                    .addComponent(btnEncap)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnHot)
                                    .addComponent(btnCold)
                                    .addComponent(btnMilktea))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(245, 234, 223));

        panelMenu.setPreferredSize(new java.awt.Dimension(567, 1000));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel7.setText("☕ MENU");

        txtsearchfield.setText("Search Drink");
        txtsearchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchfieldActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        btnSearch.setText("🔍");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(180, 279, Short.MAX_VALUE)
                .addComponent(txtsearchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(46, 46, 46))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addComponent(jLabel7))
                .addContainerGap(965, Short.MAX_VALUE))
        );

        scrollMenu.setViewportView(panelMenu);

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ITEM", "SIZE", "PRICE", "QTY", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        jLabel30.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        jLabel30.setText("🧾 YOUR ORDER");

        btnClearOrder.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        btnClearOrder.setText("🗑 Clear Order");
        btnClearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOrderActionPerformed(evt);
            }
        });

        btnCheckout.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        btnCheckout.setText("🛒 Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTotal.setText("TOTAL:");

        jSeparator2.setBackground(new java.awt.Color(120, 97, 69));

        lblTotalItems.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTotalItems.setText("Total Items:");

        txtTotalAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTotalAmt.setText("₱230.00");

        txtTotalItems.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTotalItems.setText("2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnCheckout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearOrder))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalAmt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTotalItems)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalItems)
                        .addGap(27, 27, 27))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalItems)
                    .addComponent(txtTotalItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotalAmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearOrder)
                    .addComponent(btnCheckout))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnColdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColdActionPerformed
        // TODO add your handling code here:
        selectedCategory = "Cold";
        selectedSize = null;
        btnEncap.setEnabled(true);
        btnInhe.setEnabled(true);
        btnPoly.setEnabled(true);
         loadMenu("");
    }//GEN-LAST:event_btnColdActionPerformed

    private void btnEncapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncapActionPerformed
        // TODO add your handling code here:
        selectedSize = "ENCAP";
    }//GEN-LAST:event_btnEncapActionPerformed

    private void btnInheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInheActionPerformed
        // TODO add your handling code here:
        selectedSize = "INHE";
    }//GEN-LAST:event_btnInheActionPerformed

    private void btnHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotActionPerformed
        // TODO add your handling code here:
        selectedCategory = "Hot";
        selectedSize = null;
        btnEncap.setEnabled(false);
        btnInhe.setEnabled(true);
        btnPoly.setEnabled(true);
        loadMenu("");
    }//GEN-LAST:event_btnHotActionPerformed

    private void btnPolyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolyActionPerformed
        // TODO add your handling code here:
        selectedSize = "POLY";
    }//GEN-LAST:event_btnPolyActionPerformed

    private void txtsearchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchfieldActionPerformed
        // TODO add your handling code here:
        filterMenu(txtsearchfield.getText());
    }//GEN-LAST:event_txtsearchfieldActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        filterMenu(txtsearchfield.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMilkteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilkteaActionPerformed
        // TODO add your handling code here:
        selectedCategory = "MilkTea";
        selectedSize = null;
        btnEncap.setEnabled(true);
        btnInhe.setEnabled(true);
        btnPoly.setEnabled(true);
         loadMenu(""); 
    }//GEN-LAST:event_btnMilkteaActionPerformed

    private void btnClearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOrderActionPerformed
        // TODO add your handling code here:
        currentOrder.clearOrder();
    
    // 2. Clear the table display
    tableModel.setRowCount(0);
    
    // 3. Reset the total labels
    txtTotalItems.setText("0");
    txtTotalAmt.setText("₱0.00");
    }//GEN-LAST:event_btnClearOrderActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // 1. Validate order is not empty
    if (currentOrder.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Your order is empty!\nPlease add items before checking out.",
            "Empty Order",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Create Receipt object and generate receipt
    Receipt receipt = new Receipt(currentOrder);
    String receiptText = receipt.generateReceipt();

    // 3. Display receipt
    javax.swing.JTextArea receiptArea = new javax.swing.JTextArea(receiptText);
    receiptArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));
    receiptArea.setEditable(false);
    receiptArea.setBackground(new java.awt.Color(255, 255, 240));

    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(receiptArea);
    scrollPane.setPreferredSize(new java.awt.Dimension(420, 400));

    Object[] options = {"Print", "Close"};
    int choice = javax.swing.JOptionPane.showOptionDialog(
        this,
        scrollPane,
        "OOP'S CAFE - Receipt",
        javax.swing.JOptionPane.DEFAULT_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE,
        null,
        options,
        options[1]
    );

    // 4. Print if selected
    if (choice == 0) {
        try {
            receiptArea.print();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Printing failed: " + ex.getMessage());
        }
    }

    // 5. Clear order after checkout
    currentOrder.clearOrder();
    tableModel.setRowCount(0);
    txtTotalItems.setText("0");
    txtTotalAmt.setText("₱0.00");
    }//GEN-LAST:event_btnCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oopscafeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oopscafeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oopscafeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oopscafeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oopscafeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClearOrder;
    private javax.swing.JButton btnCold;
    private javax.swing.JButton btnEncap;
    private javax.swing.JButton btnHot;
    private javax.swing.JButton btnInhe;
    private javax.swing.JButton btnMilktea;
    private javax.swing.JButton btnPoly;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JScrollPane scrollMenu;
    private javax.swing.JTable tblOrder;
    private javax.swing.JLabel txtTotalAmt;
    private javax.swing.JLabel txtTotalItems;
    private javax.swing.JTextField txtsearchfield;
    // End of variables declaration//GEN-END:variables

    private void setupTable() {
    tableModel = (DefaultTableModel) tblOrder.getModel();
    tableModel.setRowCount(0);
}

private void addToOrder(String drinkName, String type) {
    if (selectedSize == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select a size first!",
            "No Size Selected",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    Coffee drink = new Coffee(drinkName, type, 0, selectedSize, 1);
    currentOrder.addDrink(drink);
    tableModel.addRow(new Object[]{
        drink.getDrinkName(),
        drink.getSize(),
        drink.getPrice(),
        drink.getQuantity(),
        drink.calculateTotal()
    });
    txtTotalItems.setText(String.valueOf(currentOrder.getOrderList().size()));
    txtTotalAmt.setText(String.format("₱%.2f", currentOrder.computeTotal()));
}

private void loadMenu(String searchText) {
    String[][] hotDrinks = {
        {"Americano",         "/images/Hot Americano.png",         "Hot", "₱95.00",  "₱110.00"},
        {"Espresso",          "/images/Hot Espresso.png",          "Hot", "₱100.00", "₱115.00"},
        {"Latte",             "/images/Hot Latte.png",             "Hot", "₱105.00", "₱120.00"},
        {"Cappuccino",        "/images/Hot Cappuccino.png",        "Hot", "₱110.00", "₱125.00"},
        {"Caramel Macchiato", "/images/Hot Caramel Macchiato.png", "Hot", "₱125.00", "₱140.00"}
    };

    String[][] coldDrinks = {
        {"Iced Americano",         "/images/Iced Americano.jpg",         "Cold", "₱120.00", "₱140.00", "₱160.00"},
        {"Iced Latte",             "/images/Iced Latte.jpg",             "Cold", "₱130.00", "₱150.00", "₱170.00"},
        {"Iced Espresso",          "/images/Iced Espresso.jpg",          "Cold", "₱125.00", "₱145.00", "₱165.00"},
        {"Iced Cappuccino",        "/images/Iced Cappuccino.jpg",        "Cold", "₱135.00", "₱155.00", "₱175.00"},
        {"Iced Caramel Macchiato", "/images/Iced Caramel Macchiato.jpg", "Cold", "₱145.00", "₱165.00", "₱185.00"}
    };
    
    String[][] allDrinks;
    boolean isCold;
    if (selectedCategory.equals("Cold")) {
        allDrinks = coldDrinks;
        isCold = true;
    } else {
        allDrinks = hotDrinks;
        isCold = false;
    }

    java.util.List<String[]> matches = new java.util.ArrayList<>();
    for (String[] drink : allDrinks) {
        if (searchText.isEmpty() || drink[0].toLowerCase().contains(searchText)) {
            matches.add(drink);
        }
    }



    // Clear and rebuild panelMenu
    menuContentPanel.removeAll();
    
    // Top bar with MENU label, search field and button

     if (matches.isEmpty()) {
        javax.swing.JLabel noResult = new javax.swing.JLabel("No drinks found.");
        noResult.setFont(new java.awt.Font("Times New Roman", 0, 16));
        noResult.setForeground(java.awt.Color.GRAY);
        noResult.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 0));
        noResult.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        menuContentPanel.add(noResult);
    } else {
        // Header row — Cold has 3 sizes, Hot has 2
        javax.swing.JPanel headerRow = new javax.swing.JPanel(
            new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
        headerRow.setBackground(panelMenu.getBackground());
        headerRow.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        headerRow.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 30));
        javax.swing.JLabel spacer = new javax.swing.JLabel();
        spacer.setPreferredSize(new java.awt.Dimension(230, 25));
        headerRow.add(spacer);

        if (isCold) {
            javax.swing.JLabel encapHeader = new javax.swing.JLabel("ENCAP");
            encapHeader.setFont(new java.awt.Font("Times New Roman", 0, 16));
            encapHeader.setPreferredSize(new java.awt.Dimension(80, 25));
            headerRow.add(encapHeader);
        }
        javax.swing.JLabel inheHeader = new javax.swing.JLabel("INHE");
        inheHeader.setFont(new java.awt.Font("Times New Roman", 0, 16));
        inheHeader.setPreferredSize(new java.awt.Dimension(80, 25));
        javax.swing.JLabel polyHeader = new javax.swing.JLabel("POLY");
        polyHeader.setFont(new java.awt.Font("Times New Roman", 0, 16));
        polyHeader.setPreferredSize(new java.awt.Dimension(80, 25));
        headerRow.add(inheHeader);
        headerRow.add(polyHeader);
        menuContentPanel.add(headerRow);

        // Drink rows
        for (String[] data : matches) {
            javax.swing.JPanel row = new javax.swing.JPanel(
                new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
            row.setBackground(panelMenu.getBackground());
            row.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            row.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 80));

            // Image
            javax.swing.JLabel imgLabel = new javax.swing.JLabel();
            try {
                java.net.URL imgURL = getClass().getResource(data[1]);
                if (imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                    java.awt.Image img = icon.getImage().getScaledInstance(
                        60, 60, java.awt.Image.SCALE_SMOOTH);
                    imgLabel.setIcon(new javax.swing.ImageIcon(img));
                }
            } catch (Exception ex) {
                System.out.println("Image not found: " + data[0]);
            }
            imgLabel.setPreferredSize(new java.awt.Dimension(65, 65));

            // Name
            javax.swing.JLabel nameLabel = new javax.swing.JLabel(data[0]);
            nameLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
            nameLabel.setPreferredSize(new java.awt.Dimension(160, 25));

            row.add(imgLabel);
            row.add(nameLabel);

            if (isCold) {
                // ENCAP price
                javax.swing.JLabel encapPrice = new javax.swing.JLabel(data[3]);
                encapPrice.setFont(new java.awt.Font("Times New Roman", 0, 16));
                encapPrice.setPreferredSize(new java.awt.Dimension(80, 25));
                row.add(encapPrice);

                // INHE price
                javax.swing.JLabel inhePrice = new javax.swing.JLabel(data[4]);
                inhePrice.setFont(new java.awt.Font("Times New Roman", 0, 16));
                inhePrice.setPreferredSize(new java.awt.Dimension(80, 25));
                row.add(inhePrice);

                // POLY price
                javax.swing.JLabel polyPrice = new javax.swing.JLabel(data[5]);
                polyPrice.setFont(new java.awt.Font("Times New Roman", 0, 16));
                polyPrice.setPreferredSize(new java.awt.Dimension(80, 25));
                row.add(polyPrice);
            } else {
                // INHE price
                javax.swing.JLabel inhePrice = new javax.swing.JLabel(data[3]);
                inhePrice.setFont(new java.awt.Font("Times New Roman", 0, 16));
                inhePrice.setPreferredSize(new java.awt.Dimension(80, 25));
                row.add(inhePrice);

                // POLY price
                javax.swing.JLabel polyPrice = new javax.swing.JLabel(data[4]);
                polyPrice.setFont(new java.awt.Font("Times New Roman", 0, 16));
                polyPrice.setPreferredSize(new java.awt.Dimension(80, 25));
                row.add(polyPrice);
            }

            // ADD button
            javax.swing.JButton addBtn = new javax.swing.JButton("ADD");
            addBtn.setBackground(new java.awt.Color(153, 0, 0));
            addBtn.setForeground(java.awt.Color.WHITE);
            addBtn.setFont(new java.awt.Font("Tahoma", 1, 16));
            String finalName = data[0];
            String finalType = data[2];
            addBtn.addActionListener(e -> addToOrder(finalName, finalType));

            row.add(addBtn);
            menuContentPanel.add(row);
        }
    }

    menuContentPanel.revalidate();
    menuContentPanel.repaint();
    javax.swing.SwingUtilities.invokeLater(() -> {
        scrollMenu.getVerticalScrollBar().setValue(0);
    });
}

private void filterMenu(String text) {
    String searchText = text.trim().toLowerCase();
    boolean showAll = searchText.equals("search drink") || searchText.isEmpty();
    loadMenu(showAll ? "" : searchText);
}
}
    
